FROM maven:3.9.9-amazoncorretto-21-debian-bookworm AS build 
# no i dont know why this is the tag, but it works

COPY pom.xml .

RUN mvn -B dependency:go-offline


COPY src ./src

RUN mvn -B package -DskipTests

FROM openjdk:21-slim-buster

COPY --from=build target/brick-server-0.1.jar .

ENTRYPOINT ["java", "-jar", "brick-server-0.1.jar"]